### ISSUE TITLE
Error running `clean_table.py`

### ISSUE THREAD

**Issue by richpsharp** [springinnovate/pestcontrol_livingdatabase#1]
Running `clean_table.py`:

```
(py39) C:\Users\mklip\pestcontrol_livingdatabase>python clean_table.py C:\Users\mklip\pestcontrol_livingdatabase\plotdata.olive.csv --cluster_resolution 3 --min_edit_distance 2 --max_edit_distance 7 --single_word_penalty 1 --field_name technician
build clusters
generating scatter plot
create name to edit distance maps for all names
submit jobs
process results
done processing results
generating candidate_table_2_3.0.csv
generating candidate_table_3_3.0.csv
generating candidate_table_4_3.0.csv
generating candidate_table_5_3.0.csv
generating candidate_table_6_3.0.csv
generating candidate_table_7_3.0.csv
Traceback (most recent call last):
  File "C:\Users\mklip\pestcontrol_livingdatabase\clean_table.py", line 170, in <module>
    main()
  File "C:\Users\mklip\pestcontrol_livingdatabase\clean_table.py", line 141, in main
    with open(edit_distance_table_path, 'w', encoding="ISO-8859-1") as \
PermissionError: [Errno 13] Permission denied: 'candidate_table_7_3.0.csv'

(py39) C:\Users\mklip\pestcontrol_livingdatabase>python clean_table.py C:\Users\mklip\pestcontrol_livingdatabase\plotdata.olive.csv --cluster_resolution 3 -
-min_edit_distance 2 --max_edit_distance 7 --single_word_penalty 1 --field_name region
build clusters
generating scatter plot
create name to edit distance maps for all names
submit jobs
process results
done processing results
generating candidate_table_2_3.0.csv
generating candidate_table_3_3.0.csv
generating candidate_table_4_3.0.csv
generating candidate_table_5_3.0.csv
generating candidate_table_6_3.0.csv
Traceback (most recent call last):
  File "C:\Users\mklip\pestcontrol_livingdatabase\clean_table.py", line 170, in <module>
    main()
  File "C:\Users\mklip\pestcontrol_livingdatabase\clean_table.py", line 141, in main
    with open(edit_distance_table_path, 'w', encoding="ISO-8859-1") as \
PermissionError: [Errno 13] Permission denied: 'candidate_table_6_3.0.csv'

(py39) C:\Users\mklip\pestcontrol_livingdatabase>python clean_table.py C:\Users\mklip\pestcontrol_livingdatabase\plotdata.olive.csv --cluster_resolution 3 -
-min_edit_distance 2 --max_edit_distance 7 --single_word_penalty 1 --field_name cultivar
build clusters
generating scatter plot
create name to edit distance maps for all names
submit jobs
process results
done processing results
generating candidate_table_2_3.0.csv
Traceback (most recent call last):
  File "C:\Users\mklip\pestcontrol_livingdatabase\clean_table.py", line 170, in <module>
    main()
  File "C:\Users\mklip\pestcontrol_livingdatabase\clean_table.py", line 141, in main
    with open(edit_distance_table_path, 'w', encoding="ISO-8859-1") as \
PermissionError: [Errno 13] Permission denied: 'candidate_table_2_3.0.csv'

(py39) C:\Users\mklip\pestcontrol_livingdatabase>python clean_table.py C:\Users\mklip\pestcontrol_livingdatabase\plotdata.vineyards.csv --cluster_resolution
 3 --min_edit_distance 2 --max_edit_distance 7 --single_word_penalty 1 --field_name cultivar
build clusters
generating scatter plot
create name to edit distance maps for all names
submit jobs
process results
done processing results
generating candidate_table_2_3.0.csv
Traceback (most recent call last):
  File "C:\Users\mklip\pestcontrol_livingdatabase\clean_table.py", line 170, in <module>
    main()
  File "C:\Users\mklip\pestcontrol_livingdatabase\clean_table.py", line 141, in main
    with open(edit_distance_table_path, 'w', encoding="ISO-8859-1") as \
PermissionError: [Errno 13] Permission denied: 'candidate_table_2_3.0.csv'
```

**Comment by richpsharp** [comment]
This looks like the tables are open in excel when the script is run. Going to check that.

**Comment by richpsharp** [comment]
fixed long ago
